classes:
  - common
  - component.namespace
  - cluster.minikube
parameters:
  target_name: all-glob

  elasticsearch:
    image: "quay.io/pires/docker-elasticsearch-kubernetes:5.5.0"
    java_opts: "-Xms512m -Xmx512m"
    replicas: 1
    masters: 1
    roles:
      ingest:
        image: ${parameters.elasticsearch.image}
        java_opts: ${parameters.elasticsearch.java_opts}
        replicas: ${parameters.elasticsearch.replicas}
        masters: ${parameters.elasticsearch.masters}
      master:
        image: ${parameters.elasticsearch.image}
        java_opts: ${parameters.elasticsearch.java_opts}
        replicas: ${parameters.elasticsearch.replicas}
        masters: ${parameters.elasticsearch.masters}
      data:
        image: ${parameters.elasticsearch.image}
        java_opts: ${parameters.elasticsearch.java_opts}
        replicas: ${parameters.elasticsearch.replicas}
        masters: ${parameters.elasticsearch.masters}
      client:
        image: ${parameters.elasticsearch.image}
        java_opts: ${parameters.elasticsearch.java_opts}
        replicas: ${parameters.elasticsearch.replicas}
        masters: ${parameters.elasticsearch.masters}

  mysql:
    instance_name: glob_instance
    image: mysql:latest
    storage_class: standard
    storage: 10G
    users:
      root:
        password: ?{base64:targets/${parameters.target_name}/mysql/password||randomstr|base64}
        password_sha256: 
          ?{base64:targets/${parameters.target_name}/mysql/password_sha256||reveal:targets/${parameters.target_name}/mysql/password|sha256|base64}
        password_subvar: ?{base64:targets/${parameters.target_name}/mysql/subvars@var1.password}
        password_sha256_subvar: ?{base64:targets/${parameters.target_name}/mysql/subvars@var2.password_sha256}

  nginx:
    image: nginx:1:15.8
    replicas: 2

  # compile all main.jsonnet in components/
  kapitan:
    compile:
      - output_path: manifests
        input_type: jsonnet
        input_paths:
          - components/*/main.jsonnet
        output_type: yml

