parameters:
  kapitan:
    vars:
      target: ${parameters.target_name}
      namespace: ${parameters.target_name}
    compile:
      - output_path: ./copy
        input_type: copy
        input_paths:
          - components/busybox/pod.yml
      - input_type: copy
        input_paths:
          - copy_target
        output_path: ./copy
      # test copying over root output_path
      - input_type: copy
        input_paths:
          - copy_target
        output_path: .
