parameters:
  elasticsearch:
    image: "quay.io/pires/docker-elasticsearch-kubernetes:5.5.0"
    java_opts: "-Xms512m -Xmx512m"
    replicas: 1
    masters: 1
    roles:
      master:
        image: ${parameters.elasticsearch.image}
        java_opts: ${parameters.elasticsearch.java_opts}
        replicas: ${parameters.elasticsearch.replicas}
        masters: ${parameters.elasticsearch.masters}
      data:
        image: ${parameters.elasticsearch.image}
        java_opts: ${parameters.elasticsearch.java_opts}
        replicas: ${parameters.elasticsearch.replicas}
        masters: ${parameters.elasticsearch.masters}
      client:
        image: ${parameters.elasticsearch.image}
        java_opts: ${parameters.elasticsearch.java_opts}
        replicas: ${parameters.elasticsearch.replicas}
        masters: ${parameters.elasticsearch.masters}
      ingest:
        image: ${parameters.elasticsearch.image}
        java_opts: ${parameters.elasticsearch.java_opts}
        replicas: ${parameters.elasticsearch.replicas}
        masters: ${parameters.elasticsearch.masters}

  kapitan:
    vars:
      target: ${parameters.target_name}
      namespace: ${parameters.target_name}
    compile:
      - output_path: manifests
        input_type: jsonnet
        input_paths:
          - components/elasticsearch/main.jsonnet
        output_type: yml
      - output_path: scripts
        input_type: jinja2
        input_paths:
          - scripts
      - output_path: .
        input_type: jinja2
        input_paths:
          - docs/elasticsearch/README.md
